logging:
  level:
    org:
      example: TRACE

########## FGA CONFIG #########

### NO AUTH - for example purposes only!! ###
openfga:
  api-url: http://localhost:4000
  user-agent: My Custom App 12.0
  read-timeout: 30
  connect-timeout: 5s
  max-retries: 3
  minimum-retry-delay: 5
  http-version: HTTP_1_1
