name: FOSSA
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fossa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: ./gradlew build

      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          branch: ${{ github.ref_name }}

      - name: Run FOSSA tests
        uses: fossas/fossa-action@3ebcea1862c6ffbd5cf1b4d0bd6b3fe7bd6f2cac # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
